# Generated by Django 4.2.6 on 2023-10-23 12:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='betting_app.country')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=255)),
                ('firstname', models.CharField(blank=True, max_length=255, null=True)),
                ('lastname', models.CharField(blank=True, max_length=255, null=True)),
                ('image', models.ImageField(blank=True, default='static/img/profiles/default.png', null=True, upload_to='static/img/profiles')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='betting_app.country')),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_goals', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('away_goals', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('result', models.CharField(blank=True, choices=[('H', 'Home'), ('A', 'Away'), ('D', 'Draw')], max_length=1, null=True)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('slug', models.SlugField(null=True)),
                ('active', models.BooleanField(blank=True, default=True)),
                ('away_team', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='away_team', to='betting_app.team')),
                ('home_team', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='home_team', to='betting_app.team')),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='betting_app.league')),
            ],
        ),
        migrations.CreateModel(
            name='Bet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_goals', models.PositiveSmallIntegerField()),
                ('away_goals', models.PositiveSmallIntegerField()),
                ('result', models.CharField(blank=True, choices=[('H', 'Home'), ('A', 'Away'), ('D', 'Draw')], max_length=1, null=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='betting_app.game')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='betting_app.player')),
            ],
        ),
    ]
