# Generated by Django 4.2.5 on 2023-10-23 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betting_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tessst',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
