# Generated by Django 4.2.5 on 2023-10-23 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('betting_app', '0002_tessst'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tessst',
            new_name='Collection',
        ),
    ]
