# Generated by Django 4.2.5 on 2023-10-23 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('betting_app', '0003_rename_tessst_collection'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Collection',
        ),
    ]
