# Generated by Django 4.2.5 on 2023-10-23 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('betting_app', '0004_delete_collection'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='betting_app.group'),
        ),
    ]
