# Generated by Django 4.2.5 on 2023-10-23 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('betting_app', '0005_group_game_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='group',
        ),
        migrations.DeleteModel(
            name='Group',
        ),
    ]
