# Generated by Django 4.2.5 on 2023-10-24 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betting_app', '0006_remove_game_group_delete_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='name',
            field=models.CharField(default='test', max_length=200),
        ),
    ]
