# Generated by Django 4.2.5 on 2023-10-24 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betting_app', '0007_game_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='name2',
            field=models.CharField(default='test', max_length=200),
        ),
    ]
