# Generated by Django 4.2.5 on 2023-10-24 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betting_app', '0009_game_name3'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='name4',
            field=models.CharField(default='test', max_length=200),
        ),
    ]
