# Generated by Django 4.2.5 on 2023-10-24 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betting_app', '0010_game_name4'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='game',
            name='name',
        ),
        migrations.RemoveField(
            model_name='game',
            name='name2',
        ),
        migrations.RemoveField(
            model_name='game',
            name='name3',
        ),
        migrations.RemoveField(
            model_name='game',
            name='name4',
        ),
        migrations.AddField(
            model_name='game',
            name='collection',
            field=models.CharField(default='Kolejka 1', max_length=200),
        ),
    ]
