# Generated by Django 4.2.5 on 2023-10-24 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('betting_app', '0018_round_game_round'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='round',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.RESTRICT, to='betting_app.round'),
        ),
    ]
