# Generated by Django 4.2.5 on 2023-10-24 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betting_app', '0021_remove_game_round'),
    ]

    operations = [
        migrations.AlterField(
            model_name='round',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
