# Generated by Django 4.2.5 on 2023-10-24 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('betting_app', '0022_alter_round_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Round',
        ),
    ]
