# Generated by Django 4.2.5 on 2023-10-24 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('betting_app', '0025_remove_game_round'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Round',
        ),
    ]
