# Generated by Django 4.2.5 on 2023-10-24 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('betting_app', '0027_round'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='round',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='betting_app.round'),
            preserve_default=False,
        ),
    ]
