# Generated by Django 4.2.5 on 2023-10-27 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betting_app', '0028_game_round'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bet',
            name='score',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='player',
            name='image',
            field=models.ImageField(blank=True, default='profiles/default.png', null=True, upload_to='profiles/'),
        ),
    ]
