# Generated by Django 4.2.5 on 2023-10-27 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betting_app', '0029_alter_bet_score_alter_player_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bet',
            name='score',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
